# Generated by Django 2.1.7 on 2019-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('shit', models.CharField(max_length=30)),
            ],
        ),
    ]
