# Generated by Django 2.1.7 on 2019-03-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_plala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plala',
        ),
    ]
